### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by vinaybedre** [vuetifyjs/nuxt#16]
Hi,

Right after pulling via vue-cli, run npm run dev or npm run build, it results in error. See below.

```
 ERROR  Failed to compile with 11 errors                                                                        14:39:00
 error  in ./node_modules/vuetify/src/stylus/components/_app.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_app.styl:1:9
   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| .application

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_app.styl 4:14-221 13:3-17:5 14:22-229
 @ ./node_modules/vuetify/es5/components/VApp/VApp.js
 @ ./node_modules/vuetify/es5/components/VApp/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_buttons.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_buttons.styl:1:9
   1| @import '../bootstrap'
--------------^
   2| @import '../components/_ripples'
   3| @import '../theme'
   4|

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_buttons.styl 4:14-225 13:3-17:5 14:22-233
 @ ./node_modules/vuetify/es5/components/VBtn/VBtn.js
 @ ./node_modules/vuetify/es5/components/VBtn/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_cards.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_cards.styl:1:9   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| /* Themes */

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_cards.styl 4:14-223 13:3-17:5 14:22-231
 @ ./node_modules/vuetify/es5/components/VCard/VCard.js
 @ ./node_modules/vuetify/es5/components/VCard/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_content.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_content.styl:1:9
   1| @import '../bootstrap'
--------------^
   2|
   3| .content
   4|   flex: 1 1 auto

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_content.styl 4:14-225 13:3-17:5 14:22-233
 @ ./node_modules/vuetify/es5/components/VGrid/VContent.js
 @ ./node_modules/vuetify/es5/components/VGrid/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_footer.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_footer.styl:1:9
   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| footer($material)

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_footer.styl 4:14-224 13:3-17:5 14:22-232
 @ ./node_modules/vuetify/es5/components/VFooter/VFooter.js
 @ ./node_modules/vuetify/es5/components/VFooter/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_grid.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_grid.styl:1:9
   1| @import '../bootstrap'
--------------^
   2|
   3| .container
   4|   flex: 1 1 100%

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_grid.styl 4:14-222 13:3-17:5 14:22-230
 @ ./node_modules/vuetify/es5/components/VGrid/VContainer.js
 @ ./node_modules/vuetify/es5/components/VGrid/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_icons.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_icons.styl:1:9   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| /* Themes */

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_icons.styl 4:14-223 13:3-17:5 14:22-231
 @ ./node_modules/vuetify/es5/components/VIcon/VIcon.js
 @ ./node_modules/vuetify/es5/components/VIcon/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_lists.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_lists.styl:1:9   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| /* Themes */

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_lists.styl 4:14-223 13:3-17:5 14:22-231
 @ ./node_modules/vuetify/es5/components/VList/VList.js
 @ ./node_modules/vuetify/es5/components/VList/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_navigation-drawer.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_navigation-drawer.styl:1:9
   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| navigation-drawer($material)

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_navigation-drawer.styl 4:14-235 13:3-17:5 14:22-243
 @ ./node_modules/vuetify/es5/components/VNavigationDrawer/VNavigationDrawer.js
 @ ./node_modules/vuetify/es5/components/VNavigationDrawer/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_overlay.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_overlay.styl:1:9
   1| @import '../bootstrap'
--------------^
   2|
   3| .overlay
   4|   position: fixed

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_overlay.styl 4:14-225 13:3-17:5 14:22-233
 @ ./node_modules/vuetify/es5/mixins/overlayable.js
 @ ./node_modules/vuetify/es5/components/VNavigationDrawer/VNavigationDrawer.js
 @ ./node_modules/vuetify/es5/components/VNavigationDrawer/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js

 error  in ./node_modules/vuetify/src/stylus/components/_toolbar.styl

Module build failed: Error: C:\Users\i070514\dev\vuetify\nuxt\node_modules\vuetify\src\stylus\components\_toolbar.styl:1:9
   1| @import '../bootstrap'
--------------^
   2| @import '../theme'
   3|
   4| /* Theme */

failed to locate @import file C:\Users\i070514\dev\vuetify
uxt\assets\style\theme.styl

    at CachedPathEvaluator.visitImport (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\lib\evaluator.js:157:21)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitRoot (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at CachedPathEvaluator.Visitor.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.evaluate (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus\lib\renderer.js:86:26)
    at C:\Users\i070514\dev\vuetify\nuxt\node_modules\stylus-loader\index.js:165:12
    at tryCatchReject (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\i070514\dev\vuetify\nuxt\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

 @ ./node_modules/vuetify/src/stylus/components/_toolbar.styl 4:14-225 13:3-17:5 14:22-233
 @ ./node_modules/vuetify/es5/components/VToolbar/VToolbar.js
 @ ./node_modules/vuetify/es5/components/VToolbar/index.js
 @ ./plugins/vuetify.js
 @ multi vue vue-router vue-meta vuex ~/plugins/vuetify.js
```

**Comment by nekosaur** [comment]
Did you choose a-la-carte components during template creation?

**Comment by nekosaur** [comment]
I just checked full and a-la-carte versions of the template and they both compiled without errors using both `dev` and `build` commands.

**Comment by apparentvisuals** [comment]
I was having the same issue after having upgraded to 0.17. 

For me, I was adding this to an existing project and did not use the template and the error was caused by a configuration in nuxt.config.js. Commenting out the below lines solved the issue.

options: {
    theme: resolve('./assets/style/theme.styl'),
},

The file didn't exist for me since as part of the upgrade to 0.17 the theme object moved to Vue.use().

**Comment by nekosaur** [comment]
@apparentvisuals Thank you for the heads up. I'd forgotten to remove the vuetify-loader config :+1:
